blank_issues_enabled: false
contact_links:
  - name: QQ 群
    url: http://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=mYOwQP51BKu_4Xg7d08YWhVIKbAhN2Un&authKey=p3N6oq3waxO%2BuWokyRUEwNUXhS7TXNKFCUBGC6XSDcZvcUEbyHMnXRSdv9lbCGKl&noverify=0&group_code=499251252
    about: 加入 QQ 群反馈问题
  - name: MC 百科
    url: https://www.mcmod.cn/class/12453.html
    about: 前往隐藏之年²的 MC 百科界面
  - name: 苦力怕论坛
    url: https://klpbbs.com/thread-85797-1-1.html
    about: 前往隐藏之年²的苦力怕论坛帖子
