blank_issues_enabled: false
contact_links:
  - name: QQ 群
    url: https://qm.qq.com/cgi-bin/qm/qr?k=ehJSejYS4lqVbwwA0bfM1qjDMR8clyup&jump_from=webapi&authKey=02DGeTlJ7CEzt9+uK1YZTOEYERyroLi4ntYTB6qLpUoawYYtTiz8yVDwLD/aTxAO
    about: 加入 QQ 群反馈问题
  - name: MC 百科
    url: https://www.mcmod.cn/class/9862.html
    about: 前往石头工艺的 MC 百科界面
  - name: 苦力怕论坛
    url: https://klpbbs.com/thread-28013-1-1.html
    about: 前往石头工艺的苦力怕论坛帖子